apiVersion: extensions/v1beta1 
kind: deployment 
metadata:
  name: incident 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  incident 
        tier: frontend
    spec:
      containers:
       - name:  incidentservice 
         image: durgaprasad/incidentservice:latest 
         resources:
          requests:
            cpu: 100m
            memory: 100Mi
         volumeMounts:
         - name: config-volume
          mountPath: /etc/config
      volumes:
       - name: config-volume
         configMap:
         name: app-properties 
