apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: incident
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  incident
        tier: frontend
    spec:
      containers:
      - name:  incidentservice
        image: durgaprasad/incidentservice:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
     volumeMounts:
          - name: mysql
            subPath: my.cnf
            mountPath: /etc/my.cnf
      restartPolicy: Always
      volumes:
        - name: mysql
          configMap:
            name: mysql

